title: Sangah Lee 👩🏻‍💻
logo: /assets/img/logo.png
description: A computational linguist in Seoul☀️💫
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one